# Use a lightweight Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script and text files to the container
COPY scripts.py .
COPY data/ /home/data/

# Install required dependencies (if any)
RUN pip install --no-cache-dir -r requirements.txt

# Define the command to run the script
CMD ["python", "scripts.py"]
